batch_size: 64
height: 71
learning_rate: 0.001
max_text_length: 17
model_path: Models/02_captcha_to_text/202501220907
train_epochs: 1000
train_workers: 20
vocab: LFlu6TqgnHYb&Ik27CMy5ziX1_sNhJ8EV0rmR4pZKDASUeWGxjwPQvOc9fBd.a3ot
width: 181
